name: Dev deployment

on:
  workflow_dispatch:
  push:
    branches:
       - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        env:
          AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
          AWS_ECR_REPOSITORY: mercury-socket
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$IMAGE_TAG .
          docker push $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$IMAGE_TAG

      - name: Update ECS service with new image
        env:
          AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
          AWS_ECR_REPOSITORY: mercury-socket
          IMAGE_TAG: ${{ github.sha }}
          AWS_REGION: us-east-2
          CLUSTER: mercury
          SERVICE: mercury-socket-service
          FAMILY: mercury-task-definition
        run: |
          # Fetch current task definition
          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition $FAMILY --region $AWS_REGION) 
          
          # Create new task definition with updated image
          NEW_TASK_DEF=$(echo $TASK_DEFINITION | jq --arg IMAGE "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" '
            .taskDefinition |
            { 
              family: .family,
              containerDefinitions: [.containerDefinitions[] | .image = $IMAGE | .],
              requiresCompatibilities: .requiresCompatibilities,
              networkMode: .networkMode,
              cpu: .cpu,
              memory: .memory,
              executionRoleArn: .executionRoleArn,
              volumes: .volumes
            }'
          )

          # Register new task definition
          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json "$(echo $NEW_TASK_DEF)" \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text
            --region $AWS_REGION)

          # Update ECS service with new task definition
          aws ecs update-service --cluster $CLUSTER --service $SERVICE --task-definition $NEW_TASK_DEF_ARN --region $AWS_REGION
